### ISSUE TITLE
Add new features

### ISSUE THREAD

**Issue by sergioloporto** [shotforsky/react-corner-ribbon#1]
Hello, could you add at least the possibility to add a `className`.
This would be helpful to further style the corner ribbon from scss.

Also it would be great to edit the following parameters from the component props:

- font-family
- letter-spacing
- font-weight
- width

**Comment by shotforsky** [comment]
Feedback received, I will add that later~

**Comment by shotforsky** [comment]
New support has been added now, document was updated, too. Thanks for your feedback, let me know if you have any other issues.

![image](https://user-images.githubusercontent.com/14038117/116892650-9dd9c800-ac62-11eb-8041-e200313e7269.png)
